In [1]:
import numpyai as npi
import numpy as np

Ensure your API KEY is set for your LLM as an environment variable.

Ensure your API KEY is set for your LLM as an environment variable.

### Natural language imputation

In [2]:
# Sample data with NaNs
data = np.array([[1, 2, 3, 4, 5, np.nan], [np.nan, 3, 5, 3.1415, 2, 2]])
arr = npi.array(data)

### Natural language imputation

In [3]:
imputed_arr = arr.chat("Impute missing values with NumPy.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Impute missing values with NumPy.                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output array after imputation:
[[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]

Metadata:
The variable output is a numpy array with NaN values replaced by the mean of the non-NaN values in the original array.
Validation: Imputation successful, Valid: True


✓ Validation successful!

### Basic operations

In [4]:
arr2 = npi.array(data * 2)
print("Addition:\n", (arr + arr2).data)
print("Subtraction:\n", (arr - arr2).data)
print("Multiplication:\n", (arr * arr2).data)
print("Division:\n", (arr / arr2).data)


Addition:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Subtraction:
 [[-1.      -2.      -3.      -4.      -5.      -3.01415]
 [-3.01415 -3.      -5.      -3.1415  -2.      -2.     ]]
Multiplication:
 [[ 2.          8.         18.         32.         50.         18.17020044]
 [18.17020044 18.         50.         19.7380445   8.          8.        ]]
Division:
 [[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


### Scalar operations


In [5]:
print("Scalar multiplication:\n", (arr * 3).data)
print("Scalar addition:\n", (10 + arr).data)


Scalar multiplication:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Scalar addition:
 [[11.      12.      13.      14.      15.      13.01415]
 [13.01415 13.      15.      13.1415  12.      12.     ]]


### Advanced operations

In [6]:
print("Matrix multiplication:\n", (arr @ arr2.T).data)
print("Mean:\n", arr.mean(axis=0))
print("Max:\n", arr.max(axis=1))

Matrix multiplication:
 [[128.17020045 105.2169    ]
 [105.2169     121.90824495]]
Mean:
 numpyai.array(shape=(6,), dtype=float64)
Max:
 numpyai.array(shape=(2,), dtype=float64)


### Indexing, slicing, and reshaping


In [7]:
print("Slice:", arr[0, 1:4].data)
print("Reshape:\n", arr.reshape(3, 4).data)

Slice: [2. 3. 4.]
Reshape:
 [[1.      2.      3.      4.     ]
 [5.      3.01415 3.01415 3.     ]
 [5.      3.1415  2.      2.     ]]


### Complex queries

In [8]:
complex_arr = npi.array(np.random.rand(10, 10))
# Increase Max Tries for Complex Queries.
complex_arr.MAX_TRIES = 5

corr_matrix = complex_arr.chat("Compute correlation matrix")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Compute correlation matrix                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Correlation Matrix:
[[ 1.          0.45799646 -0.07534757 -0.68125148  0.08586308 -0.23461142
  -0.32912413  0.08177738  0.6861603   0.58670975]
 [ 0.45799646  1.          0.20827796  0.06710745  0.35651935 -0.15403255
  -0.4041375  -0.06942013  0.31790915  0.26665723]
 [-0.07534757  0.20827796  1.          0.51484825  0.11097359 -0.49996827
   0.08941882  0.30862134 -0.4844444   0.12959387]
 [-0.68125148  0.06710745  0.51484825  1.         -0.11807369 -0.06906067
   0.10771133 -0.1029193  -0.56672968 -0.13574218]
 [ 0.08586308  0.35651935  0.11097359 -0.11807369  1.         -0.21684007
   0.31861134  0.55273655 -0.35788114 -0.40666716]
 [-0.23461142 -0.15403255 -0.49996827 -0.06906067 -0.21684007  1.
  -0.31389051 -0.45531493  0.08282061  0.18460819]
 [-0.32912413 -0.4041375   0.08941882  0.10771133  0.31861134 -0.31389051
   1.          0.45641853 -0.57021685 -0.39098291]
 [ 0.08177738 -0.06942013  0.30862134 -0.1029193   0.55273655 -0.45531493
   0.45641853  1.         -0.57461273 -

✓ Validation successful!

In [9]:
eigen_result = complex_arr.chat("Find eigenvectors and eigenvalues")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Find eigenvectors and eigenvalues                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Eigenvalues: [ 4.86956375+0.j         -0.81148906+0.j          0.56585683+0.72450093j
  0.56585683-0.72450093j -0.22404762+0.4766903j  -0.22404762-0.4766903j
 -0.11100627+0.j          0.72147122+0.3617766j   0.72147122-0.3617766j
  0.42863917+0.j        ]
Eigenvectors: [[ 0.30515343+0.j         -0.1545949 +0.j         -0.45634741+0.j
  -0.45634741-0.j         -0.03650833-0.2848947j  -0.03650833+0.2848947j
   0.63861777+0.j         -0.47105744+0.j         -0.47105744-0.j
   0.34153812+0.j        ]
 [ 0.25032709+0.j         -0.55290295+0.j          0.17161941+0.08771013j
   0.17161941-0.08771013j  0.22967582+0.24262079j  0.22967582-0.24262079j
  -0.059117  +0.j          0.43371287-0.08756248j  0.43371287+0.08756248j
  -0.32239753+0.j        ]
 [ 0.33551778+0.j         -0.23962491+0.j          0.12270585+0.16005695j
   0.12270585-0.16005695j -0.42997607+0.j         -0.42997607-0.j
   0.13101517+0.j         -0.14245243-0.00864979j -0.14245243+0.00864979j
  -0.31812605+0.j        ]
 [ 0.358

✓ Validation successful!

### Working with Multiple Arrays

In [10]:
# Define Arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.random.random((2, 3))

In [11]:
# Start a NumpyAISession
sess = npi.NumpyAISession([arr1, arr2])

In [12]:
imputed_array = sess.chat("Impute the first array with the mean of the second array.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Impute the first array with the mean of the second array.                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[1. 2. 3.]
 [4. 5. 6.]]
The variable output is a numpy array. It is a copy of arr1, but with NaN values replaced by the mean of arr2, ensuring no NaN values are present.
Output Array:
[[1. 2. 3.]
 [4. 5. 6.]]

Metadata:
The variable output is a numpy array, where NaN, infinity, and zero values in arr1 are replaced by the mean of arr2.  arr1 was converted to float type to accommodate potential floating point mean imputation.


In [13]:
# A complex problem.
sess.chat("Multiply the second array by the sum of the fourier transform of the first array.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Multiply the second array by the sum of the fourier transform of the first array.                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output Array:
[[4.1668813 +0.j 5.10101469+0.j 2.27922249+0.j]
 [1.55711901+0.j 0.006571  +0.j 5.41696891+0.j]]

Metadata:
The variable output is a numpy array arr2 multiplied by the sum of the 2D Fourier transform of arr1.
The shape of the original arr1 is: (2, 3)
The shape of the original arr2 is: (2, 3)
The sum of the fourier transform of arr1 is: (6+0j)
The shape of the output array is: (2, 3)


C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_utils.py:97: ComplexWarning: Casting complex values to real discards the imaginary part
  "min": float(output.min()),
C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_utils.py:98: ComplexWarning: Casting complex values to real discards the imaginary part
  "max": float(output.max()),
C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_utils.py:99: ComplexWarning: Casting complex values to real discards the imaginary part
  "mean": float(output.mean()),


array([[4.1668813 +0.j, 5.10101469+0.j, 2.27922249+0.j],
       [1.55711901+0.j, 0.006571  +0.j, 5.41696891+0.j]])