In [1]:
import numpyai as npi
import numpy as np

C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Ensure your API KEY is set for your LLM as an environment variable.

### Natural language imputation

In [2]:
# Sample data with NaNs
data = np.array([[1, 2, 3, 4, 5, np.nan], [np.nan, 3, 5, 3.1415, 2, 2]])
arr = npi.array(data)

### Natural language imputation

In [3]:
imputed_arr = arr.chat("Impute missing values with NumPy.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Impute missing values with NumPy.                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/3...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Calculate the mean of the array, ignoring NaN values                                                     │
│    3 mean_val = np.nanmean(arr)                                                                                 │
│    4                                                                                                            │
│    5 # Replace NaN values with the calculated mean                                                              │
│    6 arr[np.isnan(arr)] = mean_val                                                                              │
│    7                                                                                                            │
│    8 # The imputed array is now stored in 'arr'                                                                 │
│    9 output = arr                                                                                               │
│   10 print("Imputed array:\n", output)                                                                          │
│   11 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Imputed array:
 [[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]


[[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 expected_shape = (2, 6)                                                                                    │
│    2 expected_dtype = np.float64                                                                                │
│    3                                                                                                            │
│    4 shape_valid = arr.shape == expected_shape                                                                  │
│    5 dtype_valid = arr.dtype == expected_dtype                                                                  │
│    6 nan_check = not np.isnan(code_out).any()                                                                   │
│    7                                                                                                            │
│    8 numerical_values = arr[~np.isnan(arr)]                                                                     │
│    9 imputed_array = arr.copy()                                                                                 │
│   10 imputed_array[np.isnan(imputed_array)] = np.nanmean(numerical_values)                                      │
│   11 mean_close = np.allclose(np.mean(imputed_array),np.mean(code_out),rtol=1e-5)                               │
│   12                                                                                                            │
│   13 if shape_valid and dtype_valid and nan_check and mean_close:                                               │
│   14     output = True                                                                                          │
│   15     print(f"Shape valid: {shape_valid}, Dtype valid: {dtype_valid}, No NaNs: {nan_check}, Mean close {mean │
│   16 else:                                                                                                      │
│   17     output = False                                                                                         │
│   18     print(f"Shape valid: {shape_valid}, Dtype valid: {dtype_valid}, No NaNs: {nan_check}, Mean close {mean │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Shape valid: True, Dtype valid: True, No NaNs: True, Mean close True, Valid: True


True

✓ Validation successful!

### Basic operations

In [4]:
arr2 = npi.array(data * 2)
print("Addition:\n", (arr + arr2).get_array())
print("Subtraction:\n", (arr - arr2).get_array())
print("Multiplication:\n", (arr * arr2).get_array())
print("Division:\n", (arr / arr2).get_array())


Addition:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Subtraction:
 [[-1.      -2.      -3.      -4.      -5.      -3.01415]
 [-3.01415 -3.      -5.      -3.1415  -2.      -2.     ]]
Multiplication:
 [[ 2.          8.         18.         32.         50.         18.17020044]
 [18.17020044 18.         50.         19.7380445   8.          8.        ]]
Division:
 [[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


### Scalar operations


In [5]:
print("Scalar multiplication:\n", (arr * 3).get_array())
print("Scalar addition:\n", (10 + arr).get_array())


Scalar multiplication:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Scalar addition:
 [[11.      12.      13.      14.      15.      13.01415]
 [13.01415 13.      15.      13.1415  12.      12.     ]]


### Advanced operations

In [11]:
print("Matrix multiplication:\n", (arr @ arr2.T).get_array())
print("Mean:\n", arr.mean(axis=0))
print("Max:\n", arr.max(axis=1))

Matrix multiplication:
 [[128.17020045 105.2169    ]
 [105.2169     121.90824495]]
Mean:
 numpyai.array((6,))
Max:
 numpyai.array((2,))


### Indexing, slicing, and reshaping


In [7]:
print("Slice:", arr[0, 1:4].get_array())
print("Reshape:\n", arr.reshape(3, 4).get_array())

Slice: [2. 3. 4.]
Reshape:
 [[1.      2.      3.      4.     ]
 [5.      3.01415 3.01415 3.     ]
 [5.      3.1415  2.      2.     ]]


### Complex queries

In [8]:
complex_arr = npi.array(np.random.rand(10, 10))
# Increase Max Tries for Complex Queries.
complex_arr.MAX_TRIES = 5

corr_matrix = complex_arr.chat("Compute correlation matrix")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Compute correlation matrix                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Calculate the correlation matrix using NumPy.                                                            │
│    3 # Ensure no NaN values exist before calculating the correlation matrix.                                    │
│    4 # Replace NaN values with 0 if they exist. Although the array properties say there are no NaN, this is goo │
│    5 arr[np.isnan(arr)] = 0                                                                                     │
│    6                                                                                                            │
│    7 # Calculate the correlation matrix.                                                                        │
│    8 output = np.corrcoef(arr, rowvar=False)                                                                    │
│    9                                                                                                            │
│   10 # Beautifully print the correlation matrix for explainability.                                             │
│   11 print("Correlation Matrix:")                                                                               │
│   12 print(output)                                                                                              │
│   13 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Correlation Matrix:
[[ 1.          0.19548662 -0.05022079  0.08392753  0.17758481  0.41408153
   0.22393462  0.17676274  0.11887131  0.56408314]
 [ 0.19548662  1.         -0.11075221 -0.50139319 -0.08117125  0.44016642
  -0.06484157 -0.13869177  0.40495372  0.05779975]
 [-0.05022079 -0.11075221  1.         -0.0196494   0.93174263  0.06353051
  -0.15482015  0.53184968  0.18642912 -0.21345824]
 [ 0.08392753 -0.50139319 -0.0196494   1.         -0.04048343  0.02997273
   0.07578319  0.28668848 -0.78854106  0.21055612]
 [ 0.17758481 -0.08117125  0.93174263 -0.04048343  1.          0.11200611
  -0.16376549  0.60857757  0.15124068 -0.06919141]
 [ 0.41408153  0.44016642  0.06353051  0.02997273  0.11200611  1.
  -0.46872251  0.38055987 -0.24108625  0.59001972]
 [ 0.22393462 -0.06484157 -0.15482015  0.07578319 -0.16376549 -0.46872251
   1.          0.076517    0.33402302 -0.48835609]
 [ 0.17676274 -0.13869177  0.53184968  0.28668848  0.60857757  0.38055987
   0.076517    1.         -0.2905824  -

[[ 1.          0.19548662 -0.05022079  0.08392753  0.17758481  0.41408153
   0.22393462  0.17676274  0.11887131  0.56408314]
 [ 0.19548662  1.         -0.11075221 -0.50139319 -0.08117125  0.44016642
  -0.06484157 -0.13869177  0.40495372  0.05779975]
 [-0.05022079 -0.11075221  1.         -0.0196494   0.93174263  0.06353051
  -0.15482015  0.53184968  0.18642912 -0.21345824]
 [ 0.08392753 -0.50139319 -0.0196494   1.         -0.04048343  0.02997273
   0.07578319  0.28668848 -0.78854106  0.21055612]
 [ 0.17758481 -0.08117125  0.93174263 -0.04048343  1.          0.11200611
  -0.16376549  0.60857757  0.15124068 -0.06919141]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 # Check if the output is a NumPy array with the correct shape and data type                                │
│    2 if not isinstance(code_out, np.ndarray):                                                                   │
│    3     output = False                                                                                         │
│    4     print("Output is not a NumPy array.")                                                                  │
│    5 elif code_out.shape != arr.shape:                                                                          │
│    6     output = False                                                                                         │
│    7     print(f"Shape mismatch: Expected {arr.shape}, Got {code_out.shape}")                                   │
│    8 elif code_out.dtype != arr.dtype:                                                                          │
│    9     output = False                                                                                         │
│   10     print(f"Data type mismatch: Expected {arr.dtype}, Got {code_out.dtype}")                               │
│   11 else:                                                                                                      │
│   12     # Check that the correlation matrix has 1s on the diagonal                                             │
│   13     diagonal_ones = np.allclose(np.diag(code_out), 1.0, rtol=1e-5)                                         │
│   14     print(f"Diagonal elements are ones: {diagonal_ones}")                                                  │
│   15                                                                                                            │
│   16     # Check that the correlation matrix is symmetric                                                       │
│   17     symmetric = np.allclose(code_out, code_out.T, rtol=1e-5)                                               │
│   18     print(f"Matrix is symmetric: {symmetric}")                                                             │
│   19                                                                                                            │
│   20     # Verify the range of values in the matrix                                                             │
│   21     min_val = np.min(code_out)                                                                             │
│   22     max_val = np.max(code_out)                                                                             │
│   23     range_check = (-1 <= min_val <= 1) and (-1 <= max_val <= 1)                                            │
│   24     print(f"Range check passed: {range_check}, min={min_val}, max={max_val}")                              │
│   25                                                                                                            │
│   26     output = diagonal_ones and symmetric and range_check                                                   [

Diagonal elements are ones: True
Matrix is symmetric: True
Range check passed: True, min=-0.7885410587745361, max=1.0
Overall validation result: True


True

✓ Validation successful!

In [9]:
eigen_result = complex_arr.chat("Find eigenvectors and eigenvalues")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Find eigenvectors and eigenvalues                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Calculate eigenvalues and eigenvectors                                                                   │
│    3 eigenvalues, eigenvectors = np.linalg.eig(arr)                                                             │
│    4                                                                                                            │
│    5 # Print the eigenvalues and eigenvectors                                                                   │
│    6 print("Eigenvalues:", eigenvalues)                                                                         │
│    7 print("Eigenvectors:", eigenvectors)                                                                       │
│    8                                                                                                            │
│    9 # Assign the result to the output variable                                                                 │
│   10 output = (eigenvalues, eigenvectors)                                                                       │
│   11 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Eigenvalues: [ 5.70217481+0.j          0.77587415+0.j         -0.03275004+0.66975785j
 -0.03275004-0.66975785j -0.51772364+0.35064827j -0.51772364-0.35064827j
 -0.39801589+0.j          0.18892734+0.11022653j  0.18892734-0.11022653j
  0.0437415 +0.j        ]
Eigenvectors: [[-0.26842659+0.j          0.45441505+0.j          0.39098968-0.1259563j
   0.39098968+0.1259563j  -0.13901312-0.2277191j  -0.13901312+0.2277191j
   0.36268997+0.j         -0.01191556+0.35175296j -0.01191556-0.35175296j
  -0.36518101+0.j        ]
 [-0.28571689+0.j         -0.03251628+0.j          0.4573243 +0.j
   0.4573243 -0.j         -0.22395235-0.01038863j -0.22395235+0.01038863j
   0.14631211+0.j          0.19726839-0.05497494j  0.19726839+0.05497494j
  -0.12886718+0.j        ]
 [-0.32053096+0.j         -0.05737435+0.j         -0.26370554-0.22975979j
  -0.26370554+0.22975979j -0.43888434-0.17535524j -0.43888434+0.17535524j
   0.57247814+0.j         -0.0834337 -0.33436897j -0.0834337 +0.33436897j
  -0.51648076+0.j 

(array([ 5.70217481+0.j        ,  0.77587415+0.j        ,
       -0.03275004+0.66975785j, -0.03275004-0.66975785j,
       -0.51772364+0.35064827j, -0.51772364-0.35064827j,
       -0.39801589+0.j        ,  0.18892734+0.11022653j,
        0.18892734-0.11022653j,  0.0437415 +0.j        ]), array([[-0.26842659+0.j        ,  0.45441505+0.j        
,
         0.39098968-0.1259563j ,  0.39098968+0.1259563j ,
        -0.13901312-0.2277191j , -0.13901312+0.2277191j ,
         0.36268997+0.j        , -0.01191556+0.35175296j,
        -0.01191556-0.35175296j, -0.36518101+0.j        ],
       [-0.28571689+0.j        , -0.03251628+0.j        ,

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 eigenvalues, eigenvectors = code_out                                                                       │
│    2                                                                                                            │
│    3 # Check that the shapes are as expected. Eigenvalues should be a 1D array                                  │
│    4 # with length equal to the number of rows (or columns, since it's square)                                  │
│    5 # of the original matrix.  Eigenvectors should be a square matrix with the                                 │
│    6 # same dimensions as the original.                                                                         │
│    7 eigenvalues_shape_correct = (eigenvalues.shape == (arr.shape[0],))                                         │
│    8 eigenvectors_shape_correct = (eigenvectors.shape == arr.shape)                                             │
│    9                                                                                                            │
│   10 # Check that the eigenvalues are real (or at least have negligible imaginary parts)                        │
│   11 eigenvalues_are_real = np.allclose(eigenvalues.imag, 0, atol=1e-8)                                         │
│   12                                                                                                            │
│   13 # Check that the eigenvectors are normalized (i.e., have unit length)                                      │
│   14 # The columns of the eigenvectors matrix are the eigenvectors.                                             │
│   15 # We check if their norms are close to 1.                                                                  │
│   16 eigenvector_norms = np.linalg.norm(eigenvectors, axis=0)                                                   │
│   17 eigenvectors_normalized = np.allclose(eigenvector_norms, 1.0, rtol=1e-5)                                   │
│   18                                                                                                            │
│   19 # A more robust check:  Verify A*v = lambda*v for each eigenvector v                                       │
│   20 # This tests if the eigenvectors and eigenvalues satisfy the fundamental                                   │
│   21 # definition of an eigenvector.                                                                            │
│   22 num_vectors = arr.shape[0]                                                                                 │
│   23 valid_eigenvectors = True                                                                                  │
│   24 for i in range(num_vectors):                                                                               │
│   25     v = eigenvectors[:, i]  # Extract eigenvector                                                          │
│   26     lambda_val = eigenvalues[i] # Extract eigenvalue                                                       │
│   27     Av = arr @ v  # Matrix-vector product (A*v)                                                            │
│   28     lambda_v = lambda_val * v # Scalar multiplication (lambda*v)                                           │
│   29                                                                                                            │
│   30     # Compare A*v and lambda*v                                                                             │
│   31     if not np.allclose(Av, lambda_v, rtol=1e-5, atol=1e-8):                                                │
│   32         valid_eigenvectors = False                                                                         │
│   33         break                                                                                              │
│   34                                                  

Eigenvalues shape correct: True
Eigenvectors shape correct: True
Eigenvalues are real: False
Eigenvectors normalized: True
Eigenvectors satisfy A*v = lambda*v: True
Overall validation: False


False

Attempt 2/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Compute eigenvectors and eigenvalues                                                                     │
│    3 eigenvalues, eigenvectors = np.linalg.eig(arr)                                                             │
│    4                                                                                                            │
│    5 # Print important information                                                                              │
│    6 print("Eigenvalues:", eigenvalues)                                                                         │
│    7 print("Eigenvectors:", eigenvectors)                                                                       │
│    8                                                                                                            │
│    9 # Assign to output                                                                                         │
│   10 output = (eigenvalues, eigenvectors)                                                                       │
│   11 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Eigenvalues: [ 5.70217481+0.j          0.77587415+0.j         -0.03275004+0.66975785j
 -0.03275004-0.66975785j -0.51772364+0.35064827j -0.51772364-0.35064827j
 -0.39801589+0.j          0.18892734+0.11022653j  0.18892734-0.11022653j
  0.0437415 +0.j        ]
Eigenvectors: [[-0.26842659+0.j          0.45441505+0.j          0.39098968-0.1259563j
   0.39098968+0.1259563j  -0.13901312-0.2277191j  -0.13901312+0.2277191j
   0.36268997+0.j         -0.01191556+0.35175296j -0.01191556-0.35175296j
  -0.36518101+0.j        ]
 [-0.28571689+0.j         -0.03251628+0.j          0.4573243 +0.j
   0.4573243 -0.j         -0.22395235-0.01038863j -0.22395235+0.01038863j
   0.14631211+0.j          0.19726839-0.05497494j  0.19726839+0.05497494j
  -0.12886718+0.j        ]
 [-0.32053096+0.j         -0.05737435+0.j         -0.26370554-0.22975979j
  -0.26370554+0.22975979j -0.43888434-0.17535524j -0.43888434+0.17535524j
   0.57247814+0.j         -0.0834337 -0.33436897j -0.0834337 +0.33436897j
  -0.51648076+0.j 

(array([ 5.70217481+0.j        ,  0.77587415+0.j        ,
       -0.03275004+0.66975785j, -0.03275004-0.66975785j,
       -0.51772364+0.35064827j, -0.51772364-0.35064827j,
       -0.39801589+0.j        ,  0.18892734+0.11022653j,
        0.18892734-0.11022653j,  0.0437415 +0.j        ]), array([[-0.26842659+0.j        ,  0.45441505+0.j        
,
         0.39098968-0.1259563j ,  0.39098968+0.1259563j ,
        -0.13901312-0.2277191j , -0.13901312+0.2277191j ,
         0.36268997+0.j        , -0.01191556+0.35175296j,
        -0.01191556-0.35175296j, -0.36518101+0.j        ],
       [-0.28571689+0.j        , -0.03251628+0.j        ,

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 eigenvalues, eigenvectors = code_out                                                                       │
│    2                                                                                                            │
│    3 # Check the shapes of the outputs                                                                          │
│    4 eigenvalues_shape_correct = eigenvalues.shape == (arr.shape[0],)                                           │
│    5 eigenvectors_shape_correct = eigenvectors.shape == (arr.shape[0], arr.shape[1])                            │
│    6                                                                                                            │
│    7 print(f"Eigenvalues shape correct: {eigenvalues_shape_correct}")                                           │
│    8 print(f"Eigenvectors shape correct: {eigenvectors_shape_correct}")                                         │
│    9                                                                                                            │
│   10 # Check that the eigenvectors are normalized (unit length)                                                 │
│   11 # This is an approximate check                                                                             │
│   12 norms = np.linalg.norm(eigenvectors, axis=0)                                                               │
│   13 normalized = np.allclose(norms, 1.0, rtol=1e-5)                                                            │
│   14                                                                                                            │
│   15 print(f"Eigenvectors normalized: {normalized}")                                                            │
│   16                                                                                                            │
│   17 # Verify that A*v = lambda*v for a few eigenvectors                                                        │
│   18 num_checks = min(3, arr.shape[0])  # Check for a maximum of 3 eigenvectors                                 │
│   19 valid_eigenpairs = True                                                                                    │
│   20 for i in range(num_checks):                                                                                │
│   21     v = eigenvectors[:, i]                                                                                 │
│   22     lambda_val = eigenvalues[i]                                                                            │
│   23     Av = arr @ v                                                                                           │
│   24     lambda_v = lambda_val * v                                                                              │
│   25     is_close = np.allclose(Av, lambda_v, rtol=1e-5)                                                        │
│   26     valid_eigenpairs = valid_eigenpairs and is_close                                                       │
│   27     print(f"Eigenpair {i+1} is valid: {is_close}")                                                         │
│   28                                                                                                            │
│   29 output = eigenvalues_shape_correct and [38;2;248;248;242;48;2;3

Eigenvalues shape correct: True
Eigenvectors shape correct: True
Eigenvectors normalized: True
Eigenpair 1 is valid: True
Eigenpair 2 is valid: True
Eigenpair 3 is valid: True
Final validation result: True


True

✓ Validation successful!