In [1]:
import numpyai as npi
import numpy as np

C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Ensure your API KEY is set for your LLM as an environment variable.

### Natural language imputation

In [2]:
# Sample data with NaNs
data = np.array([[1, 2, 3, 4, 5, np.nan], [np.nan, 3, 5, 3.1415, 2, 2]])
arr = npi.array(data)

### Natural language imputation

In [3]:
imputed_arr = arr.chat("Impute missing values with NumPy.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Impute missing values with NumPy.                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/3...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Calculate the mean of the array, ignoring NaN values                                                     │
│    3 mean_value = np.nanmean(arr)                                                                               │
│    4                                                                                                            │
│    5 # Replace NaN values with the mean                                                                         │
│    6 arr[np.isnan(arr)] = mean_value                                                                            │
│    7                                                                                                            │
│    8 # The imputed array is now stored in 'arr'                                                                 │
│    9 output = arr                                                                                               │
│   10 print("Imputed Array:\n", output)                                                                          │
│   11 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Imputed Array:
 [[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]


[[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 # Check that the output array has the same shape as the input array                                        │
│    2 shape_check = arr.shape == code_out.shape                                                                  │
│    3                                                                                                            │
│    4 # Check that there are no NaN values in the output array                                                   │
│    5 nan_check = not np.isnan(code_out).any()                                                                   │
│    6                                                                                                            │
│    7 # Calculate the number of NaN values in the original array                                                 │
│    8 nan_count_original = np.isnan(arr).sum()                                                                   │
│    9                                                                                                            │
│   10 # Calculate the number of non-NaN values in the original array                                             │
│   11 valid_values_original = arr[~np.isnan(arr)]                                                                │
│   12                                                                                                            │
│   13 # Calculate the mean of the valid values in the original array                                             │
│   14 mean_original = np.mean(valid_values_original)                                                             │
│   15                                                                                                            │
│   16 # Create an array where NaNs are replaced with the original mean                                           │
│   17 filled_arr = np.nan_to_num(arr, nan=mean_original)                                                         │
│   18                                                                                                            │
│   19 # Check if the output array is close to the filled array                                                   │
│   20 close_check = np.allclose(code_out, filled_arr, rtol=1e-5)                                                 │
│   21                                                                                                            │
│   22 output = shape_check and nan_check and close_check                                                         │
│   23                                                                                                            │
│   24 print(f"Shape check: {shape_check}, NaN check: {nan_check}, Close check: {close_check}, Valid: {output}")  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Shape check: True, NaN check: True, Close check: True, Valid: True


True

✓ Validation successful!

### Basic operations

In [4]:
arr2 = npi.array(data * 2)
print("Addition:\n", (arr + arr2).get_array())
print("Subtraction:\n", (arr - arr2).get_array())
print("Multiplication:\n", (arr * arr2).get_array())
print("Division:\n", (arr / arr2).get_array())


Addition:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Subtraction:
 [[-1.      -2.      -3.      -4.      -5.      -3.01415]
 [-3.01415 -3.      -5.      -3.1415  -2.      -2.     ]]
Multiplication:
 [[ 2.          8.         18.         32.         50.         18.17020044]
 [18.17020044 18.         50.         19.7380445   8.          8.        ]]
Division:
 [[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


### Scalar operations


In [5]:
print("Scalar multiplication:\n", (arr * 3).get_array())
print("Scalar addition:\n", (10 + arr).get_array())


Scalar multiplication:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Scalar addition:
 [[11.      12.      13.      14.      15.      13.01415]
 [13.01415 13.      15.      13.1415  12.      12.     ]]


### Advanced operations

In [6]:
print("Matrix multiplication:\n", (arr @ arr2.T).get_array())
print("Mean:\n", arr.mean(axis=0))
print("Max:\n", arr.max(axis=1))

Matrix multiplication:
 [[128.17020045 105.2169    ]
 [105.2169     121.90824495]]
Mean:
 numpyai.array((6,))
Max:
 numpyai.array((2,))


### Indexing, slicing, and reshaping


In [7]:
print("Slice:", arr[0, 1:4].get_array())
print("Reshape:\n", arr.reshape(3, 4).get_array())

Slice: [2. 3. 4.]
Reshape:
 [[1.      2.      3.      4.     ]
 [5.      3.01415 3.01415 3.     ]
 [5.      3.1415  2.      2.     ]]


### Complex queries

In [8]:
complex_arr = npi.array(np.random.rand(10, 10))
# Increase Max Tries for Complex Queries.
complex_arr.MAX_TRIES = 5

corr_matrix = complex_arr.chat("Compute correlation matrix")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Compute correlation matrix                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Ensure no NaN or infinite values exist (though the description says there aren't any)                    │
│    3 arr = np.nan_to_num(arr)                                                                                   │
│    4                                                                                                            │
│    5 # Calculate the correlation matrix using NumPy                                                             │
│    6 correlation_matrix = np.corrcoef(arr, rowvar=False)                                                        │
│    7                                                                                                            │
│    8 # Assign the correlation matrix to the output variable                                                     │
│    9 output = correlation_matrix                                                                                │
│   10                                                                                                            │
│   11 # Print the correlation matrix for explanation                                                             │
│   12 print("Correlation Matrix:")                                                                               │
│   13 print(output)                                                                                              │
│   14 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Correlation Matrix:
[[ 1.         -0.08135795  0.17696691  0.45218551 -0.07676118 -0.09096991
  -0.24185732  0.38020601 -0.18743377 -0.20220048]
 [-0.08135795  1.          0.27913924  0.15754822  0.13388651  0.06151992
   0.13645088  0.18607863 -0.03419175  0.86941498]
 [ 0.17696691  0.27913924  1.          0.10748666 -0.28026988 -0.05243572
  -0.35304624 -0.37143395 -0.10185635  0.32508083]
 [ 0.45218551  0.15754822  0.10748666  1.         -0.46887925 -0.17124446
  -0.06932051  0.54864757 -0.22246948  0.04700024]
 [-0.07676118  0.13388651 -0.28026988 -0.46887925  1.          0.12400322
  -0.22431419  0.26174401  0.32716493  0.27427643]
 [-0.09096991  0.06151992 -0.05243572 -0.17124446  0.12400322  1.
   0.07888138  0.13337369  0.48723081  0.24710153]
 [-0.24185732  0.13645088 -0.35304624 -0.06932051 -0.22431419  0.07888138
   1.         -0.16981543 -0.08584125 -0.1454399 ]
 [ 0.38020601  0.18607863 -0.37143395  0.54864757  0.26174401  0.13337369
  -0.16981543  1.         -0.24519061  

[[ 1.         -0.08135795  0.17696691  0.45218551 -0.07676118 -0.09096991
  -0.24185732  0.38020601 -0.18743377 -0.20220048]
 [-0.08135795  1.          0.27913924  0.15754822  0.13388651  0.06151992
   0.13645088  0.18607863 -0.03419175  0.86941498]
 [ 0.17696691  0.27913924  1.          0.10748666 -0.28026988 -0.05243572
  -0.35304624 -0.37143395 -0.10185635  0.32508083]
 [ 0.45218551  0.15754822  0.10748666  1.         -0.46887925 -0.17124446
  -0.06932051  0.54864757 -0.22246948  0.04700024]
 [-0.07676118  0.13388651 -0.28026988 -0.46887925  1.          0.12400322
  -0.22431419  0.26174401  0.32716493  0.27427643]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 if arr.ndim == 2 and code_out.shape == (arr.shape[1], arr.shape[1]):                                       │
│    2     # Check that the correlation matrix has 1s along the diagonal                                          │
│    3     diagonal_values = np.diag(code_out)                                                                    │
│    4     diag_ones = np.allclose(diagonal_values, 1.0, rtol=1e-5)                                               │
│    5     print(f"Diagonal values are ones: {diag_ones}")                                                        │
│    6                                                                                                            │
│    7     # Check that the correlation matrix is symmetric                                                       │
│    8     is_symmetric = np.allclose(code_out, code_out.T, rtol=1e-5)                                            │
│    9     print(f"Matrix is symmetric: {is_symmetric}")                                                          │
│   10                                                                                                            │
│   11     # Check that values are between -1 and 1 (inclusive). Slight tolerance is added due to potential float │
│   12     within_range = np.all((code_out >= -1.0 - 1e-6) & (code_out <= 1.0 + 1e-6))                            │
│   13     print(f"All values are within [-1, 1]: {within_range}")                                                │
│   14                                                                                                            │
│   15     output = diag_ones and is_symmetric and within_range                                                   │
│   16                                                                                                            │
│   17 else:                                                                                                      │
│   18     output = False                                                                                         │
│   19     print("Shape mismatch or not 2D array")                                                                │
│   20                                                                                                            │
│   21 print(f"Final validation result: {output}")                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Diagonal values are ones: True
Matrix is symmetric: True
All values are within [-1, 1]: True
Final validation result: True


True

✓ Validation successful!

In [9]:
eigen_result = complex_arr.chat("Find eigenvectors and eigenvalues")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Find eigenvectors and eigenvalues                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Compute eigenvalues and eigenvectors                                                                     │
│    3 eigenvalues, eigenvectors = np.linalg.eig(arr)                                                             │
│    4                                                                                                            │
│    5 # Store the result in the 'output' variable                                                                │
│    6 output = (eigenvalues, eigenvectors)                                                                       │
│    7                                                                                                            │
│    8 # Print the shapes and a few values for inspection                                                         │
│    9 print(f"Eigenvalues shape: {eigenvalues.shape}")                                                           │
│   10 print(f"Eigenvectors shape: {eigenvectors.shape}")                                                         │
│   11 print(f"First few eigenvalues: {eigenvalues[:3]}")                                                         │
│   12 print(f"First few eigenvectors (first column): {eigenvectors[:, 0][:3]}")                                  │
│   13 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Eigenvalues shape: (10,)
Eigenvectors shape: (10, 10)
First few eigenvalues: [ 4.67277858+0.j        -1.01811677+0.j         0.05927149+0.6173977j]
First few eigenvectors (first column): [0.34473615+0.j 0.35595568+0.j 0.31479473+0.j]


(array([ 4.67277858+0.j        , -1.01811677+0.j        ,
        0.05927149+0.6173977j ,  0.05927149-0.6173977j ,
        0.50449294+0.48922418j,  0.50449294-0.48922418j,
        0.58921947+0.j        , -0.40957023+0.j        ,
       -0.06981609+0.03473467j, -0.06981609-0.03473467j]), array([[ 0.34473615+0.j        ,  0.50760329+0.j        
,
        -0.50944974+0.j        , -0.50944974-0.j        ,
         0.41023286-0.03522094j,  0.41023286+0.03522094j,
         0.12336479+0.j        ,  0.03169483+0.j        ,
        -0.06305389+0.01445112j, -0.06305389-0.01445112j],
       [ 0.35595568+0.j        , -0.29211   +0.j        ,

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 eigenvalues, eigenvectors = code_out                                                                       │
│    2                                                                                                            │
│    3 # Check that the shapes are as expected.                                                                   │
│    4 eigenvalues_shape_correct = eigenvalues.shape == (10,)                                                     │
│    5 eigenvectors_shape_correct = eigenvectors.shape == (10, 10)                                                │
│    6                                                                                                            │
│    7 # Check that the eigenvectors are normalized (unit length). Due to possible                                │
│    8 # complex values, compare the sum of squares of absolute values to 1.                                      │
│    9 eigenvectors_normalized = np.allclose(np.sum(np.abs(eigenvectors)**2, axis=0), 1, rtol=1e-5)               │
│   10                                                                                                            │
│   11 # Check that A*v = lambda*v for a few eigenvectors.  This verifies that the                                │
│   12 # eigenvalues and eigenvectors are consistent with the original matrix. We will pick                       │
│   13 # the first two eigenvectors to test.                                                                      │
│   14 num_vectors_to_test = min(2, eigenvectors.shape[1])                                                        │
│   15 consistent_eigenvectors = True                                                                             │
│   16 for i in range(num_vectors_to_test):                                                                       │
│   17     v = eigenvectors[:, i]                                                                                 │
│   18     lambda_val = eigenvalues[i]                                                                            │
│   19     Av = arr @ v                                                                                           │
│   20     lambda_v = lambda_val * v                                                                              │
│   21     consistent_eigenvectors = consistent_eigenvectors and np.allclose(Av, lambda_v, rtol=1e-5)             │
│   22                                                                                                            │
│   23 output = (                                                                                                 │
│   24     eigenvalues_shape_correct                                                                              │
│   25     and eigenvectors_shape_correct                                                                         │
│   26     and eigenvectors_normalized                                                                            │
│   27     and consistent_eigenvectors                                                                            │
│   28 )                                                                                                          │
│   29                                                                                                            │
│   30 print(f"Eigenvalues shape correct: {eigenvalues_shape_correct}")                                           │
│   31 print(f"Eigenvectors shape correct: {eigenvectors_shape_correct}")                                         │
│   32 print(f"Eigenvectors normalized: {eigenvectors_normalized}")                                               │
│   33 print[38;2;248;248;242;48;2;39;40

Eigenvalues shape correct: True
Eigenvectors shape correct: True
Eigenvectors normalized: True
Eigenvectors consistent with eigenvalues and original matrix: True
Overall validation: True


True

✓ Validation successful!