In [2]:
import numpyai as npi
import numpy as np

Ensure your API KEY is set for your LLM as an environment variable.

Ensure your API KEY is set for your LLM as an environment variable.

### Natural language imputation

In [2]:
# Sample data with NaNs
data = np.array([[1, 2, 3, 4, 5, np.nan], [np.nan, 3, 5, 3.1415, 2, 2]])
arr = npi.array(data)

### Natural language imputation

In [3]:
imputed_arr = arr.chat("Impute missing values with NumPy.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Impute missing values with NumPy.                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/3...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Calculate the mean of the array, ignoring NaN values                                                     │
│    3 mean_val = np.nanmean(arr)                                                                                 │
│    4                                                                                                            │
│    5 # Replace NaN values with the calculated mean                                                              │
│    6 arr[np.isnan(arr)] = mean_val                                                                              │
│    7                                                                                                            │
│    8 # The imputed array is now stored in the 'output' variable                                                 │
│    9 output = arr                                                                                               │
│   10                                                                                                            │
│   11 # Print the imputed array                                                                                  │
│   12 print("Imputed Array:\n", output)                                                                          │
│   13 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Imputed Array:
 [[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]


[[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 # Check that NaNs are no longer present                                                                    │
│    2 nan_check = not np.isnan(code_out).any()                                                                   │
│    3                                                                                                            │
│    4 # Check the shape of the output array                                                                      │
│    5 shape_check = code_out.shape == arr.shape                                                                  │
│    6                                                                                                            │
│    7 # Check that the min/max are still within the original range. If NaN was replaced with a value outside     │
│    8 # this range, it would immediately fail.                                                                   │
│    9 min_check = np.min(code_out) >= np.nanmin(arr)                                                             │
│   10 max_check = np.max(code_out) <= np.nanmax(arr)                                                             │
│   11                                                                                                            │
│   12 # Calculate the number of original NaNs                                                                    │
│   13 num_nans_original = np.sum(np.isnan(arr))                                                                  │
│   14                                                                                                            │
│   15 # Calculate the mean of the imputed array and compare it with a pre-calculated mean                        │
│   16 # based on properties, taking into account the number of NaN values.                                       │
│   17 # This avoids recomputing the same operation.                                                              │
│   18 expected_mean = 3.0141500000000003 # Value derived from properties                                         │
│   19                                                                                                            │
│   20 mean_check = np.isclose(np.mean(code_out), expected_mean, rtol=1e-5)                                       │
│   21                                                                                                            │
│   22 output = nan_check and shape_check and min_check and max_check and mean_check                              │
│   23                                                                                                            │
│   24 print(f"NaN check: {nan_check}, Shape check: {shape_check}, Min check: {min_check}, Max check: {max_check} │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

NaN check: True, Shape check: True, Min check: True, Max check: True, Mean Check: True, Valid: True


True

✓ Validation successful!

### Basic operations

In [5]:
arr2 = npi.array(data * 2)
print("Addition:\n", (arr + arr2).data)
print("Subtraction:\n", (arr - arr2).data)
print("Multiplication:\n", (arr * arr2).data)
print("Division:\n", (arr / arr2).data)


Addition:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Subtraction:
 [[-1.      -2.      -3.      -4.      -5.      -3.01415]
 [-3.01415 -3.      -5.      -3.1415  -2.      -2.     ]]
Multiplication:
 [[ 2.          8.         18.         32.         50.         18.17020044]
 [18.17020044 18.         50.         19.7380445   8.          8.        ]]
Division:
 [[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


### Scalar operations


In [6]:
print("Scalar multiplication:\n", (arr * 3).data)
print("Scalar addition:\n", (10 + arr).data)


Scalar multiplication:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Scalar addition:
 [[11.      12.      13.      14.      15.      13.01415]
 [13.01415 13.      15.      13.1415  12.      12.     ]]


### Advanced operations

In [7]:
print("Matrix multiplication:\n", (arr @ arr2.T).data)
print("Mean:\n", arr.mean(axis=0))
print("Max:\n", arr.max(axis=1))

Matrix multiplication:
 [[128.17020045 105.2169    ]
 [105.2169     121.90824495]]
Mean:
 numpyai.array(shape=(6,), dtype=float64)
Max:
 numpyai.array(shape=(2,), dtype=float64)


### Indexing, slicing, and reshaping


In [8]:
print("Slice:", arr[0, 1:4].data)
print("Reshape:\n", arr.reshape(3, 4).data)

Slice: [2. 3. 4.]
Reshape:
 [[1.      2.      3.      4.     ]
 [5.      3.01415 3.01415 3.     ]
 [5.      3.1415  2.      2.     ]]


### Complex queries

In [9]:
complex_arr = npi.array(np.random.rand(10, 10))
# Increase Max Tries for Complex Queries.
complex_arr.MAX_TRIES = 5

corr_matrix = complex_arr.chat("Compute correlation matrix")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Compute correlation matrix                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # The array 'arr' is already defined.                                                                      │
│    3 # Calculate the correlation matrix using NumPy.                                                            │
│    4 # Ensure no NaN values exist before computing the correlation.                                             │
│    5 arr[np.isnan(arr)] = 0  # Replace NaN values with 0 if any exist (precautionary).  There aren't any accord │
│    6 output = np.corrcoef(arr, rowvar=False)                                                                    │
│    7                                                                                                            │
│    8 # Print the correlation matrix                                                                             │
│    9 print("Correlation Matrix:")                                                                               │
│   10 print(output)                                                                                              │
│   11 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Correlation Matrix:
[[ 1.          0.58964626 -0.15842099 -0.67634366 -0.49967754  0.45607361
   0.09139427  0.18045659 -0.4511771   0.35243851]
 [ 0.58964626  1.          0.13962728 -0.15168474 -0.60787333  0.53833137
  -0.58217327  0.31807251 -0.202653    0.19543926]
 [-0.15842099  0.13962728  1.         -0.17489315  0.25521676 -0.54384755
  -0.31935429 -0.07491143 -0.35842858 -0.26822347]
 [-0.67634366 -0.15168474 -0.17489315  1.          0.21840753  0.06059137
  -0.47711845  0.05827428  0.40751681 -0.08199293]
 [-0.49967754 -0.60787333  0.25521676  0.21840753  1.         -0.22296715
   0.09370987 -0.55408219  0.29573423  0.11064891]
 [ 0.45607361  0.53833137 -0.54384755  0.06059137 -0.22296715  1.
  -0.18291825  0.04371694  0.25410011  0.67804924]
 [ 0.09139427 -0.58217327 -0.31935429 -0.47711845  0.09370987 -0.18291825
   1.         -0.1083652  -0.21105661  0.22511104]
 [ 0.18045659  0.31807251 -0.07491143  0.05827428 -0.55408219  0.04371694
  -0.1083652   1.          0.0082501  -

[[ 1.          0.58964626 -0.15842099 -0.67634366 -0.49967754  0.45607361
   0.09139427  0.18045659 -0.4511771   0.35243851]
 [ 0.58964626  1.          0.13962728 -0.15168474 -0.60787333  0.53833137
  -0.58217327  0.31807251 -0.202653    0.19543926]
 [-0.15842099  0.13962728  1.         -0.17489315  0.25521676 -0.54384755
  -0.31935429 -0.07491143 -0.35842858 -0.26822347]
 [-0.67634366 -0.15168474 -0.17489315  1.          0.21840753  0.06059137
  -0.47711845  0.05827428  0.40751681 -0.08199293]
 [-0.49967754 -0.60787333  0.25521676  0.21840753  1.         -0.22296715
   0.09370987 -0.55408219  0.29573423  0.11064891]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 # Validate correlation matrix properties: diagonal should be ones, and matrix should be symmetric.         │
│    2 if arr.ndim == 2:                                                                                          │
│    3     # Check if the diagonal elements are close to 1.0                                                      │
│    4     diag_ones = np.allclose(np.diag(code_out), 1.0, rtol=1e-5)                                             │
│    5     print(f"Diagonal elements are ones: {diag_ones}")                                                      │
│    6                                                                                                            │
│    7     # Check if the correlation matrix is symmetric                                                         │
│    8     symmetry = np.allclose(code_out, code_out.T, rtol=1e-5)                                                │
│    9     print(f"Correlation matrix is symmetric: {symmetry}")                                                  │
│   10                                                                                                            │
│   11     # Combine the checks for final validation                                                              │
│   12     output = diag_ones and symmetry                                                                        │
│   13     print(f"Overall validation: {output}")                                                                 │
│   14 else:                                                                                                      │
│   15     output = False                                                                                         │
│   16     print("Input array is not 2D, validation failed.")                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Diagonal elements are ones: True
Correlation matrix is symmetric: True
Overall validation: True


True

✓ Validation successful!

In [10]:
eigen_result = complex_arr.chat("Find eigenvectors and eigenvalues")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Find eigenvectors and eigenvalues                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Attempt 1/5...

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 ```python                                                                                                  │
│    2 # Calculate eigenvalues and eigenvectors                                                                   │
│    3 eigenvalues, eigenvectors = np.linalg.eig(arr)                                                             │
│    4                                                                                                            │
│    5 # Print eigenvalues and eigenvectors for inspection                                                        │
│    6 print("Eigenvalues:", eigenvalues)                                                                         │
│    7 print("Eigenvectors:", eigenvectors)                                                                       │
│    8                                                                                                            │
│    9 # Assign the result to the output variable                                                                 │
│   10 output = (eigenvalues, eigenvectors)                                                                       │
│   11 ```                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Executing generated code...

Eigenvalues: [ 4.90337724+0.j         -0.06791453+0.77335378j -0.06791453-0.77335378j
 -0.66572709+0.43842943j -0.66572709-0.43842943j -0.46448822+0.j
  0.14422968+0.26919363j  0.14422968-0.26919363j  0.5524318 +0.j
  0.33349775+0.j        ]
Eigenvectors: [[ 0.29006199+0.j         -0.47994736+0.j         -0.47994736-0.j
   0.05128631-0.08420632j  0.05128631+0.08420632j -0.44309064+0.j
  -0.29784309+0.27524228j -0.29784309-0.27524228j -0.0906815 +0.j
   0.10672964+0.j        ]
 [ 0.22376039+0.j          0.10909555+0.07259357j  0.10909555-0.07259357j
  -0.29400217-0.09169993j -0.29400217+0.09169993j -0.09712608+0.j
   0.50789184+0.j          0.50789184-0.j         -0.20274663+0.j
   0.44836326+0.j        ]
 [ 0.37860097+0.j          0.29216227-0.11762781j  0.29216227+0.11762781j
   0.01576271+0.46478803j  0.01576271-0.46478803j  0.24357964+0.j
  -0.33331979+0.03310107j -0.33331979-0.03310107j  0.36651269+0.j
  -0.17044606+0.j        ]
 [ 0.29870107+0.j         -0.11821292-0.23382004j -0.

(array([ 4.90337724+0.j        , -0.06791453+0.77335378j,
       -0.06791453-0.77335378j, -0.66572709+0.43842943j,
       -0.66572709-0.43842943j, -0.46448822+0.j        ,
        0.14422968+0.26919363j,  0.14422968-0.26919363j,
        0.5524318 +0.j        ,  0.33349775+0.j        ]), array([[ 0.29006199+0.j        , -0.47994736+0.j        
,
        -0.47994736-0.j        ,  0.05128631-0.08420632j,
         0.05128631+0.08420632j, -0.44309064+0.j        ,
        -0.29784309+0.27524228j, -0.29784309-0.27524228j,
        -0.0906815 +0.j        ,  0.10672964+0.j        ],
       [ 0.22376039+0.j        ,  0.10909555+0.07259357j,

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 eigenvalues, eigenvectors = code_out                                                                       │
│    2                                                                                                            │
│    3 # 1. Check the shape of the output. Eigenvalues should be a 1D array of length arr.shape[0].               │
│    4 # Eigenvectors should be a 2D array with shape arr.shape.                                                  │
│    5 eigenvalues_shape_correct = eigenvalues.shape == (arr.shape[0],)                                           │
│    6 eigenvectors_shape_correct = eigenvectors.shape == arr.shape                                               │
│    7                                                                                                            │
│    8 print(f"Eigenvalues shape correct: {eigenvalues_shape_correct}")                                           │
│    9 print(f"Eigenvectors shape correct: {eigenvectors_shape_correct}")                                         │
│   10                                                                                                            │
│   11 # 2. Verify that A*v = lambda*v for a few eigenvectors/eigenvalues                                         │
│   12 num_checks = min(3, arr.shape[0])  # Check at most 3 eigenvector/eigenvalue pairs                          │
│   13 valid_eigenvectors = True                                                                                  │
│   14 for i in range(num_checks):                                                                                │
│   15     v = eigenvectors[:, i]  # Extract eigenvector                                                          │
│   16     lambda_val = eigenvalues[i]  # Extract eigenvalue                                                      │
│   17                                                                                                            │
│   18     # Compute A*v                                                                                          │
│   19     av = arr @ v                                                                                           │
│   20                                                                                                            │
│   21     # Compute lambda*v                                                                                     │
│   22     lambda_v = lambda_val * v                                                                              │
│   23                                                                                                            │
│   24     # Check if A*v is close to lambda*v                                                                    │
│   25     is_eigenvector = np.allclose(av, lambda_v, rtol=1e-5, atol=1e-8)                                       │
│   26     print(f"Eigenvector {i+1} is valid: {is_eigenvector}")                                                 │
│   27     valid_eigenvectors = valid_eigenvectors and is_eigenvector                                             │
│   28                                                                                                            │
│   29 # 3. Check if the eigenvectors are normalized (approximately).                                             │
│   30 # Because in some edge cases this assumption does not hold strictly, avoid this check for now.             │
│   31                                                                                                            │
│   32 output = eigenvalues_shape_correct and eigenvectors_shape_correct and valid_eigenvectors                   │
│   33 print(f"Final Validation: {output}")                                                                       │
[3

Eigenvalues shape correct: True
Eigenvectors shape correct: True
Eigenvector 1 is valid: True
Eigenvector 2 is valid: True
Eigenvector 3 is valid: True
Final Validation: True


True

✓ Validation successful!

### Working with Multiple Arrays

In [6]:
# Define Arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.random.random((2, 3))

In [7]:
# Start a NumpyAISession
sess = npi.NumpyAISession([arr1, arr2])

In [8]:
imputed_array = sess.chat("Impute the first array with the mean of the second array.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Impute the first array with the mean of the second array.                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 1/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 mean_arr2 = np.mean(arr2)                                                                                   │
│   2 arr1 = arr1.astype(np.float64)                                                                              │
│   3 arr1[np.isnan(arr1)] = mean_arr2                                                                            │
│   4 output = np.nan_to_num(arr1, nan=mean_arr2)                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[1. 2. 3.]
 [4. 5. 6.]]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│   1 mean_arr2 = np.mean(arr2)                                                                                   │
│   2 expected_arr1 = arr1.astype(np.float64)                                                                     │
│   3 output = np.allclose(np.where(np.isnan(expected_arr1), mean_arr2, expected_arr1), code_out, rtol=1e-05)     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

True

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation Successful.                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [14]:
# A complex problem.
sess.chat("Multiply the second array by the sum of the fourier transform of the first array.")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Multiply the second array by the sum of the fourier transform of the first array.                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 1/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 fft_arr1 = np.fft.fft2(arr1)                                                                                │
│   2 sum_fft_arr1 = np.sum(fft_arr1)                                                                             │
│   3 output = arr2 * sum_fft_arr1                                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[5.41524096+0.j 2.78459039+0.j 2.98248167+0.j]
 [2.92732782+0.j 1.61608396+0.j 4.39203762+0.j]]

C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_utils.py:81: ComplexWarning: Casting complex values to real discards the imaginary part
  "min": float(output.min()),
C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_utils.py:82: ComplexWarning: Casting complex values to real discards the imaginary part
  "max": float(output.max()),
C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_utils.py:83: ComplexWarning: Casting complex values to real discards the imaginary part
  "mean": float(output.mean()),


╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 arr1_fft = np.fft.fft2(arr1)                                                                               │
│    2 fft_sum = np.sum(arr1_fft)                                                                                 │
│    3 expected_dtype = np.complex128                                                                             │
│    4 expected_shape = arr2.shape                                                                                │
│    5 output = True                                                                                              │
│    6                                                                                                            │
│    7 if code_out.dtype != expected_dtype:                                                                       │
│    8     output = False                                                                                         │
│    9 elif code_out.shape != expected_shape:                                                                     │
│   10     output = False                                                                                         │
│   11 else:                                                                                                      │
│   12     reconstructed_arr2 = code_out / fft_sum                                                                │
│   13     if not np.allclose(arr2, reconstructed_arr2, rtol=1e-5):                                               │
│   14         output = False                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

True

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation Successful.                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

array([[5.41524096+0.j, 2.78459039+0.j, 2.98248167+0.j],
       [2.92732782+0.j, 1.61608396+0.j, 4.39203762+0.j]])