In [1]:
import numpyai as npi
import numpy as np

C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[18:08:16] Ensure your API KEY is set for your LLM as an environment variable.                         ]8;id=556327;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=353169;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#13\13]8;;\

### Natural language imputation

In [2]:
# Sample data with NaNs
data = np.array([[1, 2, 3, 4, 5, np.nan], [np.nan, 3, 5, 3.1415, 2, 2]])
arr = npi.array(data)

### Natural language imputation

In [3]:
imputed_arr = arr.chat("Impute missing values with NumPy.")

[18:08:29] llm response is:                                                                           ]8;id=364526;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=897781;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#534\534]8;;\
            ```python                                                                                              
           # Calculate the mean of the array, ignoring NaN values                                                  
           mean_val = np.nanmean(arr)                                                                              
           print(f"Mean value (ignoring NaNs): {mean_val}")                                                        
                                                                                                                   
           # Replace NaN values with the calculated mean                                                           
           arr = mean_val                                                                                          
           print(f"Array after NaN imputation:\n{arr}")                                                            
                                                                                                                   
           output = arr                                                                                            
           ```                                                                                                     

           The following code will be executed:                                                       ]8;id=835496;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=506654;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#553\553]8;;\
            # Calculate the mean of the array, ignoring NaN values                                                 
           mean_val = np.nanmean(arr)                                                                              
           print(f"Mean value (ignoring NaNs): {mean_val}")                                                        
                                                                                                                   
           # Replace NaN values with the calculated mean                                                           
           arr = mean_val                                                                                          
           print(f"Array after NaN imputation:\n{arr}")                                                            
                                                                                                                   
           output = arr                                                                                            

Mean value (ignoring NaNs): 3.01415
Array after NaN imputation:
[[1.      2.      3.      4.      5.      3.01415]
 [3.01415 3.      5.      3.1415  2.      2.     ]]


[18:08:30] The following code will be executed as validation/test:                                    ]8;id=8458;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=345949;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#475\475]8;;\
                                   arr_copy = arr.copy()                                                           
           mean_val = np.nanmean(arr_copy)                                                                         
           arr_copy = mean_val                                                                                     
           output = np.allclose(arr_copy, code_out, rtol=1e-5)                                                     
           print(f"Validation result: {output}")                                                                   
                                                                                                                   

Validation result: True


### Basic operations

In [13]:
arr2 = npi.array(data * 2)
print("Addition:\n", (arr + arr2).get_array())
print("Subtraction:\n", (arr - arr2).get_array())
print("Multiplication:\n", (arr * arr2).get_array())
print("Division:\n", (arr / arr2).get_array())


Addition:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Subtraction:
 [[-1.      -2.      -3.      -4.      -5.      -3.01415]
 [-3.01415 -3.      -5.      -3.1415  -2.      -2.     ]]
Multiplication:
 [[ 2.          8.         18.         32.         50.         18.17020044]
 [18.17020044 18.         50.         19.7380445   8.          8.        ]]
Division:
 [[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


### Scalar operations


In [14]:
print("Scalar multiplication:\n", (arr * 3).get_array())
print("Scalar addition:\n", (10 + arr).get_array())


Scalar multiplication:
 [[ 3.       6.       9.      12.      15.       9.04245]
 [ 9.04245  9.      15.       9.4245   6.       6.     ]]
Scalar addition:
 [[11.      12.      13.      14.      15.      13.01415]
 [13.01415 13.      15.      13.1415  12.      12.     ]]


### Advanced operations

In [15]:
print("Matrix multiplication:\n", (arr @ arr2.T).get_array())
print("Mean:\n", arr.mean(axis=0))
print("Max:\n", arr.max(axis=1))


Matrix multiplication:
 [[128.17020045 105.2169    ]
 [105.2169     121.90824495]]
Mean:
 numpyai.array(array([2.007075, 2.5     , 4.      , 3.57075 , 3.5     , 2.507075]))
Max:
 numpyai.array(array([5., 5.]))


### Indexing, slicing, and reshaping


In [16]:
print("Slice:", arr[0, 1:4].get_array())
print("Reshape:\n", arr.reshape(3, 4).get_array())


Slice: [2. 3. 4.]
Reshape:
 [[1.      2.      3.      4.     ]
 [5.      3.01415 3.01415 3.     ]
 [5.      3.1415  2.      2.     ]]


### Complex queries

In [9]:
complex_arr = npi.array(np.random.rand(10, 10))
corr_matrix = complex_arr.chat("Compute correlation matrix")
eigen_result = complex_arr.chat("Find eigenvectors and eigenvalues")


[18:09:49] llm response is:                                                                           ]8;id=705585;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=393348;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#534\534]8;;\
            ```python                                                                                              
           # Compute correlation matrix.                                                                           
           print(f"Original array:\n{arr}")                                                                        
                                                                                                                   
           # Calculate the correlation matrix using numpy.                                                         
           output = np.corrcoef(arr, rowvar=False)                                                                 
                                                                                                                   
           print(f"\nCorrelation matrix:\n{output}")                                                               
           ```                                                                                                     

           The following code will be executed:                                                       ]8;id=875441;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=280825;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#553\553]8;;\
            # Compute correlation matrix.                                                                          
           print(f"Original array:\n{arr}")                                                                        
                                                                                                                   
           # Calculate the correlation matrix using numpy.                                                         
           output = np.corrcoef(arr, rowvar=False)                                                                 
                                                                                                                   
           print(f"\nCorrelation matrix:\n{output}")                                                               

Original array:
[[0.35621169 0.96315431 0.57247549 0.99959103 0.1043437  0.48543476
  0.60564853 0.11598363 0.82189312 0.56695423]
 [0.71515345 0.89988139 0.49972876 0.25169273 0.62441811 0.62330053
  0.33417679 0.72046772 0.50280066 0.16801271]
 [0.26164029 0.61727539 0.78775447 0.10729519 0.61233365 0.85109564
  0.8383163  0.74209611 0.30188497 0.65887609]
 [0.21684702 0.56319493 0.03945928 0.01440208 0.47375635 0.83319574
  0.24517333 0.72969469 0.99264858 0.02121741]
 [0.13361035 0.14716417 0.48706611 0.58546173 0.52901522 0.99815891
  0.07754633 0.78834893 0.90887559 0.56741674]
 [0.3653243  0.79909509 0.19006931 0.14366219 0.81754594 0.7447024
  0.98187151 0.88058333 0.64838479 0.98622271]
 [0.28929606 0.59774347 0.21873757 0.55379776 0.47593991 0.62634475
  0.51655071 0.42234461 0.01650188 0.11862765]
 [0.27512362 0.14627626 0.09289911 0.15211097 0.36172982 0.17054085
  0.64419701 0.52317973 0.44246678 0.81209053]
 [0.34043903 0.4915635  0.15338572 0.18532114 0.40946561 0.358694

[18:09:50] The following code will be executed as validation/test:                                    ]8;id=768696;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=195744;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#475\475]8;;\
                                   arr_centered = arr - np.mean(arr, axis=0)                                       
           arr_normalized = arr_centered / np.std(arr, axis=0)                                                     
           expected_output = np.corrcoef(arr.T)                                                                    
                                                                                                                   
           output = np.allclose(expected_output, code_out, rtol=1e-05)                                             
           print(f"Validation Result: {output}")                                                                   
                                                                                                                   

Validation Result: True


[18:09:51] llm response is:                                                                           ]8;id=152955;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=371762;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#534\534]8;;\
            ```python                                                                                              
           # Calculate eigenvalues and eigenvectors                                                                
           eigenvalues, eigenvectors = np.linalg.eig(arr)                                                          
                                                                                                                   
           # Assign the result to the output variable                                                              
           output = (eigenvalues, eigenvectors)                                                                    
                                                                                                                   
           # Print the eigenvalues and eigenvectors                                                                
           print("Eigenvalues:", eigenvalues)                                                                      
           print("Eigenvectors:", eigenvectors)                                                                    
           ```                                                                                                     

           The following code will be executed:                                                       ]8;id=129123;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=86701;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#553\553]8;;\
            # Calculate eigenvalues and eigenvectors                                                               
           eigenvalues, eigenvectors = np.linalg.eig(arr)                                                          
                                                                                                                   
           # Assign the result to the output variable                                                              
           output = (eigenvalues, eigenvectors)                                                                    
                                                                                                                   
           # Print the eigenvalues and eigenvectors                                                                
           print("Eigenvalues:", eigenvalues)                                                                      
           print("Eigenvectors:", eigenvectors)                                                                    

Eigenvalues: [ 4.88882599+0.j          0.80738661+0.j          0.57068678+0.21201191j
  0.57068678-0.21201191j -0.39414207+0.66245957j -0.39414207-0.66245957j
 -0.38812781+0.34462683j -0.38812781-0.34462683j -0.14370904+0.11546517j
 -0.14370904-0.11546517j]
Eigenvectors: [[ 0.34878931+0.j         -0.61789809+0.j          0.42170566+0.21906345j
   0.42170566-0.21906345j -0.0366672 -0.20888495j -0.0366672 +0.20888495j
  -0.55456842+0.j         -0.55456842-0.j         -0.38700738+0.16036078j
  -0.38700738-0.16036078j]
 [ 0.34259644+0.j         -0.43549578+0.j          0.15172187+0.2164049j
   0.15172187-0.2164049j   0.07627457-0.01552199j  0.07627457+0.01552199j
   0.32845789+0.1065615j   0.32845789-0.1065615j   0.38246007-0.08575342j
   0.38246007+0.08575342j]
 [ 0.37714917+0.j          0.13200251+0.j         -0.63895405+0.j
  -0.63895405-0.j         -0.00143973+0.12265548j -0.00143973-0.12265548j
  -0.03604642-0.06770091j -0.03604642+0.06770091j -0.08620058+0.01558497j
  -0.08620058-0.0

[18:09:53] The following code will be executed as validation/test:                                    ]8;id=295405;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py\_array.py]8;;\:]8;id=47413;file://C:\Users\aadya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpyai\_array.py#475\475]8;;\
                                   w, v = np.linalg.eig(arr)                                                       
           print(f"Eigenvalues: {w}")                                                                              
           print(f"Eigenvectors: {v}")                                                                             
                                                                                                                   
           eigenvalues_close = np.allclose(w, code_out[0], rtol=1e-05)                                             
           eigenvectors_close = np.allclose(v, code_out[1], rtol=1e-05)                                            
                                                                                                                   
           output = eigenvalues_close and eigenvectors_close                                                       
                                                                                                                   
           print(f"Eigenvalues close: {eigenvalues_close}")                                                        
           print(f"Eigenvectors close: {eigenvectors_close}")                                                      
           print(f"Validation result: {output}")                                                                   
                                                                                                                   

Eigenvalues: [ 4.88882599+0.j          0.80738661+0.j          0.57068678+0.21201191j
  0.57068678-0.21201191j -0.39414207+0.66245957j -0.39414207-0.66245957j
 -0.38812781+0.34462683j -0.38812781-0.34462683j -0.14370904+0.11546517j
 -0.14370904-0.11546517j]
Eigenvectors: [[ 0.34878931+0.j         -0.61789809+0.j          0.42170566+0.21906345j
   0.42170566-0.21906345j -0.0366672 -0.20888495j -0.0366672 +0.20888495j
  -0.55456842+0.j         -0.55456842-0.j         -0.38700738+0.16036078j
  -0.38700738-0.16036078j]
 [ 0.34259644+0.j         -0.43549578+0.j          0.15172187+0.2164049j
   0.15172187-0.2164049j   0.07627457-0.01552199j  0.07627457+0.01552199j
   0.32845789+0.1065615j   0.32845789-0.1065615j   0.38246007-0.08575342j
   0.38246007+0.08575342j]
 [ 0.37714917+0.j          0.13200251+0.j         -0.63895405+0.j
  -0.63895405-0.j         -0.00143973+0.12265548j -0.00143973-0.12265548j
  -0.03604642-0.06770091j -0.03604642+0.06770091j -0.08620058+0.01558497j
  -0.08620058-0.0