In [1]:
from sklearn.datasets import load_iris
import numpy as np
import numpyai as npi

from rich.console import Console

Ensure your API KEY is set for your LLM as an environment variable.

Ensure your API KEY is set for your LLM as an environment variable.

In [2]:
c = Console() 

In [3]:
iris = load_iris()
X, y = iris.data, iris.target
print(isinstance(X, np.ndarray) and isinstance(y, np.ndarray))

True


In [4]:
sess = npi.NumpyAISession([X, y], verbose=False)
diag = npi.Diagnosis(sess)

In [5]:
steps = diag.steps(task="Give me the exact and pithy steps to decide which machine learning model to use. You should not give more than seven steps.")

────────────────────────────────────────────────── LLM Response ───────────────────────────────────────────────────

╭────────────────────────────────────────────── Data Analysis Steps ──────────────────────────────────────────────╮
│ [ "1. Analyze class distribution: Use unique with return_counts=True on 'arr2' to see the balance of classes.   │
│ If highly imbalanced, consider stratified sampling or using cost-sensitive learning in later modeling stages.   │
│ If balanced, proceed to step 2.", "2. Calculate descriptive statistics: Use mean, std, min, max, and percentile │
│ on each column of 'arr1'. This helps understand the data's range and central tendencies, potentially revealing  │
│ outliers or data entry errors. If outliers are present, consider capping or winsorizing them based on the data  │
│ distribution and domain knowledge.", "3. Check for multicollinearity: Calculate the correlation matrix using    │
│ corrcoef on 'arr1'. High correlation (e.g., >0.7 or <-0.7) between features suggests multicollinearity. If      │
│ present, consider removing one of the correlated features or using dimensionality reduction techniques like     │
│ PCA.", "4. Feature importance assessment: Use a simple model like DecisionTreeClassifier or LogisticRegression  │
│ with L1 regularization (feature selection) and evaluate feature importances or coefficients. Features with very │
│ low importance scores might be dropped to simplify the model.", "5. Data dimensionality assessment: use PCA     │
│ using PCA from sklearn.decomposition module. If the first two components do not explain at least 70% of the     │
│ variance, the data cannot be easily visualized.", "6. Initial Model Selection: Based on the class distribution  │
│ and data characteristics (linearity, feature importance), choose a few suitable models. If the relationship     │
│ between the features and target variable is linear and multicollinearity is not present, go for                 │
│ LogisticRegression. If the relation is non-linear, go for RandomForestClassifier or                             │
│ GradientBoostingClassifier.", "7. Model Validation Strategy: Split the data into training, validation, and test │
│ sets. If class imbalance is significant, use stratified splitting to maintain class proportions in each set.    │
│ Use Cross validation such as StratifiedKFold if you have less data for training." ]                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [6]:
for step in steps:
    try:
        sess.chat(step)
    except:
        c.print(f"The following step failed: {step}")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 1. Analyze class distribution: Use `unique` with `return_counts=True` on 'arr2' to see the balance of    │
│ classes. If highly imbalanced, consider stratified sampling or using cost-sensitive learning in later modeling  │
│ stages. If balanced, proceed to step 2.                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Class Distribution:
Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples

Class distribution appears relatively balanced.
Class Distribution:
Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples

Class Proportions:
Class 0: 0.33
Class 1: 0.33
Class 2: 0.33


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 2. Calculate descriptive statistics: Use `mean`, `std`, `min`, `max`, and `percentile` on each column of │
│ 'arr1'. This helps understand the data's range and central tendencies, potentially revealing outliers or data   │
│ entry errors. If outliers are present, consider capping or winsorizing them based on the data distribution and  │
│ domain knowledge.                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Class Distribution:
Class 0: 0.3333
Class 1: 0.3333
Class 2: 0.3333
Means: [5.84333333 3.05733333 3.758      1.19933333]
Standard Deviations: [0.82530129 0.43441097 1.75940407 0.75969263]
Mins: [4.3 2.  1.  0.1]
Maxs: [7.9 4.4 6.9 2.5]
25th Percentiles: [5.1 2.8 1.6 0.3]
50th Percentiles (Medians): [5.8  3.   4.35 1.3 ]
75th Percentiles: [6.4 3.3 5.1 1.8]


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 3. Check for multicollinearity: Calculate the correlation matrix using `corrcoef` on 'arr1'. High        │
│ correlation (e.g., >0.7 or <-0.7) between features suggests multicollinearity. If present, consider removing    │
│ one of the correlated features or using dimensionality reduction techniques like PCA.                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Correlation Matrix:
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
Correlation Matrix of arr1:
 [[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 4. Feature importance assessment: Use a simple model like `DecisionTreeClassifier` or                    │
│ `LogisticRegression` with L1 regularization (feature selection) and evaluate feature importances or             │
│ coefficients. Features with very low importance scores might be dropped to simplify the model.                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Feature importances: [0.         0.01333333 0.06405596 0.92261071]
Feature Importances: [0.01333333 0.         0.56405596 0.42261071]
Class Labels: [0 1 2]
Class Counts: [50 50 50]
Class Probabilities: [0.33333333 0.33333333 0.33333333]
Feature Importances: [0.02666667 0.         0.05072262 0.92261071]
Shape match: True
Dtype match: True
Has NaN: False
Has Inf: False
Sum close to one: True


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Output                                                                                                          │
│  <class 'numpy.ndarray'>                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 5. Data dimensionality assessment: use PCA using `PCA` from `sklearn.decomposition` module. If the first │
│ two components do not explain at least 70% of the variance, the data cannot be easily visualized.               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Explained variance ratio for the first two components: [0.92461872 0.05306648]
Total explained variance: 0.9776852063187963
The first two components explain at least 70% of the variance. Data can be easily visualized.
Explained variance ratio for the first two components: [0.92461872 0.05306648]
Total explained variance by the first two components: 0.9776852063187963
The first two components explain at least 70% of the variance. The data can be easily visualized.
Explained Variance Ratio: [0.92461872 0.05306648]
Total Explained Variance (2 components): 0.9776852063187963
Data is easily visualizable (>= 70% variance explained): True


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 6. Initial Model Selection: Based on the class distribution and data characteristics (linearity, feature │
│ importance), choose a few suitable models. If the relationship between the features and target variable is      │
│ linear and multicollinearity is not present, go for `LogisticRegression`. If the relation is non-linear, go for │
│ `RandomForestClassifier` or `GradientBoostingClassifier`.                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Class Distribution:
 [0.33333333 0.33333333 0.33333333]

Correlation Matrix:
 [[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]

Are there highly correlated features? True

Model Selection: RandomForestClassifier or GradientBoostingClassifier (assuming a non-linear relationship or multicollinearity)
PCA is not defined, assuming easy_visualize is False.
Class distribution: [0.33333333 0.33333333 0.33333333]
High Correlation: True
Easy to visualize data: False
Selected models: ['RandomForestClassifier' 'GradientBoostingClassifier']
Class Distribution:
Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples

Descriptive Statistics for each column of arr1:
Means: [5.84333333 3.05733333 3.758      1.19933333]
Standard Deviations: [0.82530129 0.43441097 1.75940407 0.75969263]
Minimums: [4.3 2.  1.  0.1]
Maximums: [7.9 4.4 6.9 2.5]
25th

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Output                                                                                                          │
│  <class 'numpy.ndarray'>                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: 7. Model Validation Strategy: Split the data into training, validation, and test sets. If class          │
│ imbalance is significant, use stratified splitting to maintain class proportions in each set. Use Cross         │
│ validation such as `StratifiedKFold` if you have less data for training.                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Class Distribution: {np.int64(0): np.int64(50), np.int64(1): np.int64(50), np.int64(2): np.int64(50)}
Class Proportions: {np.int64(0): np.float64(0.3333333333333333), np.int64(1): np.float64(0.3333333333333333), np.int64(2): np.float64(0.3333333333333333)}
Should use StratifiedKFold: False
Number of Splits: 5
Shape of arr1: (150, 4)
Shape of arr2: (150,)
Output: [  5 150 150]
Class Distribution:
Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples
Class Distribution:
Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples
The dataset is relatively balanced.

Class Proportions:
Class 0: 0.3333
Class 1: 0.3333
Class 2: 0.3333
Class Proportions: [0.33333333 0.33333333 0.33333333]
Class Proportions: [0.33333333 0.33333333 0.33333333]


╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✗ Attempt 3 failed: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

                                                   Error Details                                                   
╔═════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Attempt │ Error                                                                                                 ║
╟─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 1       │ Attempt 1: list index out of range                                                                    ║
║ 2       │ Attempt 2: The truth value of an array with more than one element is ambiguous. Use a.any() or        ║
║         │ a.all()                                                                                               ║
║ 3       │ Attempt 3: The truth value of an array with more than one element is ambiguous. Use a.any() or        ║
║         │ a.all()                                                                                               ║
╚═════════╧═══════════════════════════════════════════════════════════════════════════════════════════════════════╝

The following step failed: 7. Model Validation Strategy: Split the data into training, validation, and test sets. 
If class imbalance is significant, use stratified splitting to maintain class proportions in each set. Use Cross 
validation such as `StratifiedKFold` if you have less data for training.