In [1]:
from sklearn.datasets import load_iris
import numpy as np
import numpyai as npi

Ensure your API KEY is set for your LLM as an environment variable.

Ensure your API KEY is set for your LLM as an environment variable.

In [2]:
iris = load_iris()
X, y = iris.data, iris.target
print(isinstance(X, np.ndarray) and isinstance(y, np.ndarray))

True


In [3]:
sess = npi.NumpyAISession([X, y])
diag = npi.Diagnosis(sess)

In [4]:
diag.steps(task="Give me the exact and pithy steps to decide which machine learning model to use.")

────────────────────────────────────────────────── LLM Response ───────────────────────────────────────────────────

╭────────────────────────────────────────────── Data Analysis Steps ──────────────────────────────────────────────╮
│                                                                                                                 │
│  1 Check class distribution in arr2: Use unique with the return_counts=True argument to determine the number of │
│    instances for each class. If the classes are imbalanced, consider using stratified sampling during           │
│    train/test split or employing techniques like SMOTE to balance the classes before training a machine         │
│    learning model. If the distribution is heavily skewed to a specific label, you might consider a model that   │
│    is robust to imbalanced data, like tree-based algorithms with class weighting.                               │
│  2 Calculate descriptive statistics of arr1: Use mean, median, std, min, and max along each column (feature).   │
│    This provides a basic understanding of the data's central tendency, spread, and range. If there are large    │
│    differences between the mean and the median, that may indicate skewed data.                                  │
│  3 Check for outliers in arr1: Calculate the Z-score for each data point using zscore. Flag data points with an │
│    absolute Z-score above a threshold (e.g., 3) as potential outliers. If outliers are detected, consider       │
│    winsorizing, trimming, or transformation techniques. If the outliers are due to mistakes in the data         │
│    collection, remove them or correct them.                                                                     │
│  4 Calculate correlation between features in arr1: Use corrcoef to determine the correlation matrix of the      │
│    features. High correlation (positive or negative) suggests multicollinearity, which can affect the           │
│    performance of linear models. If highly correlated features are identified, consider using PCA for           │
│    dimensionality reduction, or using regularization to penalize large coefficients.                            │
│  5 Evaluate feature importance with a tree-based model: Use a DecisionTreeClassifier or RandomForestClassifier  │
│    from scikit-learn to train a simple model predicting arr2 using arr1 as features. Inspect the                │
│    feature_importances_ attribute of the trained model to get an estimate of feature importance. If one or a    │
│    few features dominate, consider feature selection or dimensionality reduction techniques.                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

"1.  **Check class distribution in `arr2`:** Use `unique` with the `return_counts=True` argument to determine the number of instances for each class. If the classes are imbalanced, consider using stratified sampling during train/test split or employing techniques like SMOTE to balance the classes before training a machine learning model. If the distribution is heavily skewed to a specific label, you might consider a model that is robust to imbalanced data, like tree-based algorithms with class weighting.\n\n2.  **Calculate descriptive statistics of `arr1`:** Use `mean`, `median`, `std`, `min`, and `max` along each column (feature). This provides a basic understanding of the data's central tendency, spread, and range. If there are large differences between the mean and the median, that may indicate skewed data.\n\n3.  **Check for outliers in `arr1`:** Calculate the Z-score for each data point using `zscore`. Flag data points with an absolute Z-score above a threshold (e.g., 3) as potent

In [4]:
sess.chat("""Check for class imbalance in the second array:
        Print if there is a class imbalance.""")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Check for class imbalance in the second array:                                                           │
│         Print if there is a class imbalance.                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 1/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 unique_labels, counts = np.unique(arr2, return_counts=True)                                                 │
│   2 if np.any(counts < (arr2.size * 0.1)):                                                                      │
│   3     output = "Class imbalance detected"                                                                     │
│   4 else:                                                                                                       │
│   5     output = "No class imbalance detected"                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

No class imbalance detected

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✗ Attempt 1 failed: list index out of range                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 2/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 class_counts = np.unique(arr2, return_counts=True)[1]                                                       │
│   2 max_count = np.max(class_counts)                                                                            │
│   3 min_count = np.min(class_counts)                                                                            │
│   4                                                                                                             │
│   5 if max_count / min_count > 2:                                                                               │
│   6   output = "Class imbalance detected"                                                                       │
│   7 else:                                                                                                       │
│   8   output = "No significant class imbalance"                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

No significant class imbalance

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 class_counts = np.unique(arr2, return_counts=True)[1]                                                      │
│    2 total_samples = arr2.size                                                                                  │
│    3 imbalance_ratio = np.max(class_counts) / total_samples                                                     │
│    4                                                                                                            │
│    5 if imbalance_ratio > 0.95:                                                                                 │
│    6     expected_output = "Significant class imbalance"                                                        │
│    7 else:                                                                                                      │
│    8     expected_output = "No significant class imbalance"                                                     │
│    9                                                                                                            │
│   10 output = expected_output == 'No significant class imbalance'                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

True

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation Successful.                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

'No significant class imbalance'

The response given above signifies no class imbalance in the output labels.

In [7]:
sess.chat("""Calculate descriptive statistics of the first array: Use mean, median, std, min, and max along each column.
Print if there is a large difference between mean and median determining skewed data.""")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Calculate descriptive statistics of the first array: Use mean, median, std, min, and max along each      │
│ column.                                                                                                         │
│ Print if there is a large difference between mean and median determining skewed data.                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 1/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 mean_arr1 = np.mean(arr1, axis=0)                                                                          │
│    2 median_arr1 = np.median(arr1, axis=0)                                                                      │
│    3 std_arr1 = np.std(arr1, axis=0)                                                                            │
│    4 min_arr1 = np.min(arr1, axis=0)                                                                            │
│    5 max_arr1 = np.max(arr1, axis=0)                                                                            │
│    6                                                                                                            │
│    7 # Check if there is a large difference between mean and median                                             │
│    8 skew_threshold = 0.5  # Define a threshold for skewness                                                    │
│    9 skewed = False                                                                                             │
│   10 for i in range(arr1.shape[1]):                                                                             │
│   11     if np.abs(mean_arr1[i] - median_arr1[i]) > skew_threshold:                                             │
│   12         skewed = True                                                                                      │
│   13         break                                                                                              │
│   14                                                                                                            │
│   15 if skewed:                                                                                                 │
│   16     output = "Data is significantly skewed"                                                                │
│   17 else:                                                                                                      │
│   18     output = "Data is not significantly skewed"                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Data is significantly skewed

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✗ Attempt 1 failed: list index out of range                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 2/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│    1 means = np.mean(arr1, axis=0)                                                                              │
│    2 medians = np.median(arr1, axis=0)                                                                          │
│    3 std_devs = np.std(arr1, axis=0)                                                                            │
│    4 mins = np.min(arr1, axis=0)                                                                                │
│    5 maxs = np.max(arr1, axis=0)                                                                                │
│    6                                                                                                            │
│    7 diffs = np.abs(means - medians)                                                                            │
│    8 threshold = std_devs * 0.5                                                                                 │
│    9                                                                                                            │
│   10 if np.any(diffs > threshold):                                                                              │
│   11     output = "Data is significantly skewed"                                                                │
│   12 else:                                                                                                      │
│   13     output = "Data is not significantly skewed"                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Data is not significantly skewed

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 means = np.mean(arr1, axis=0)                                                                              │
│    2 medians = np.median(arr1, axis=0)                                                                          │
│    3 diff = np.abs(means - medians)                                                                             │
│    4 threshold = np.mean(np.std(arr1, axis=0))                                                                  │
│    5                                                                                                            │
│    6 skewed = np.any(diff > threshold)                                                                          │
│    7                                                                                                            │
│    8 if skewed:                                                                                                 │
│    9     expected_code_out = "Data is significantly skewed"                                                     │
│   10 else:                                                                                                      │
│   11     expected_code_out = "Data is not significantly skewed"                                                 │
│   12                                                                                                            │
│   13 output = code_out == expected_code_out                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

True

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation Successful.                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

'Data is not significantly skewed'

Okay, there is no skewness right now.

In [4]:
# Now, we'll remove the outliers.
X_new = sess.chat("""Replace outliers in arr1.""")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Replace outliers in arr1.                                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 1/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 # Replace outliers in arr1 using the interquartile range (IQR) method.                                      │
│   2 Q1 = np.percentile(arr1, 25, axis=0)                                                                        │
│   3 Q3 = np.percentile(arr1, 75, axis=0)                                                                        │
│   4 IQR = Q3 - Q1                                                                                               │
│   5 lower_bound = Q1 - 1.5 * IQR                                                                                │
│   6 upper_bound = Q3 + 1.5 * IQR                                                                                │
│   7                                                                                                             │
│   8 # Clip values outside the bounds to the lower or upper bound.                                               │
│   9 output = np.clip(arr1, lower_bound, upper_bound)                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[5.1  3.5  1.4  0.2 ]
 [4.9  3.   1.4  0.2 ]
 [4.7  3.2  1.3  0.2 ]
 [4.6  3.1  1.5  0.2 ]
 [5.   3.6  1.4  0.2 ]
 [5.4  3.9  1.7  0.4 ]
 [4.6  3.4  1.4  0.3 ]
 [5.   3.4  1.5  0.2 ]
 [4.4  2.9  1.4  0.2 ]
 [4.9  3.1  1.5  0.1 ]
... (output truncated)

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✗ Attempt 1 failed: list index out of range                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 2/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 threshold = 3                                                                                               │
│   2 mean = np.mean(arr1)                                                                                        │
│   3 std = np.std(arr1)                                                                                          │
│   4 z_scores = np.abs((arr1 - mean) / std)                                                                      │
│   5 outliers = z_scores > threshold                                                                             │
│   6 arr1[outliers] = mean                                                                                       │
│   7 output = arr1                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
... (output truncated)

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 # Replace outliers in arr1 using the interquartile range (IQR) method.                                     │
│    2 # First, calculate the IQR for each column.                                                                │
│    3 q1 = np.percentile(arr1, 25, axis=0)                                                                       │
│    4 q3 = np.percentile(arr1, 75, axis=0)                                                                       │
│    5 iqr = q3 - q1                                                                                              │
│    6                                                                                                            │
│    7 # Define the outlier bounds.                                                                               │
│    8 lower_bound = q1 - 1.5 * iqr                                                                               │
│    9 upper_bound = q3 + 1.5 * iqr                                                                               │
│   10                                                                                                            │
│   11 # Clip values outside the outlier bounds to the bounds.                                                    │
│   12 output = np.copy(arr1) # Operate on a copy to avoid modifying original array.                              │
│   13 for i in range(arr1.shape[1]):                                                                             │
│   14     output[:, i] = np.clip(output[:, i], lower_bound[i], upper_bound[i])                                   │
│   15                                                                                                            │
│   16                                                                                                            │
│   17                                                                                                            │
│   18 # Verification code:                                                                                       │
│   19                                                                                                            │
│   20 # 1. Check if the output shape is the same as the input array.                                             │
│   21 shape_check = arr1.shape == code_out.shape                                                                 │
│   22                                                                                                            │
│   23 # 2. Check for NaN or Inf values. Since the original array has neither, the output shouldn't either after  │
│   24 nan_check = not np.any(np.isnan(code_out))                                                                 │
│   25 inf_check = not np.any(np.isinf(code_out))                                                                 │
│   26                                                                                                            │
│   27 # 3. Check that the minimum and maximum values are within a reasonable range after outlier handling. Clipp │
│   28 min_original = np.min(arr1)                                                                                │
│   29 max_original = np.max(arr1)                                                                                │
│   30 min_modified = np.min(code_out)                                                                            │
│   31 max_modified = np.max(code_out)                                                                            │
│   32                                                                                                            │
│   33 [38;2;248;248;242;48;2;39;

True

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation Successful.                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Output                                                                                                          │
│  <class 'numpy.ndarray'>                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Outliers replaced.

In [5]:
# Start a new session with the new array.
new_sess = npi.NumpyAISession([X_new, y])

In [6]:
new_sess.chat("""Calculate correlation between features in the first array: Use corrcoef to determine the correlation matrix of the      
features.""")

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Query: Calculate correlation between features in the first array: Use corrcoef to determine the correlation     │
│ matrix of the                                                                                                   │
│ features.                                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 1/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 output = np.corrcoef(arr1.T)                                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✗ Attempt 1 failed: list index out of range                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Attempt 2/3...                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Generated Code ─────────────────────────────────────────────────╮
│   1 output = np.corrcoef(arr1.T)                                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]

╭──────────────────────────────────────────────── Validation Code ────────────────────────────────────────────────╮
│    1 output = False                                                                                             │
│    2 if isinstance(code_out, np.ndarray):                                                                       │
│    3     if code_out.shape == (4, 4):                                                                           │
│    4         if code_out.dtype == np.float64:                                                                   │
│    5             if not np.isnan(code_out).any() and not np.isinf(code_out).any():                              │
│    6                 # Check that the diagonal is all ones (correlation with itself)                            │
│    7                 if np.allclose(np.diag(code_out), 1.0):                                                    │
│    8                     # Check for symmetry                                                                   │
│    9                     if np.allclose(code_out, code_out.T, rtol=1e-05):                                      │
│   10                         output = True                                                                      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

True

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation Successful.                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Output                                                                                                          │
│  <class 'numpy.ndarray'>                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

A lot of columns have high correlation which might suggest multi-collinearity. Hence, it might be useful to use regularization with linear models or PCA as suggested by `numpyai.Diagnosis.steps`.